### PR TITLE
fix(app): properly show all versions and notify loaders

### LINKED ISSUE #3821: "Show all versions" in the download dialog should be checked by default if the project only supports snapshots
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues?q=is%3Aissue) for duplicate problems
- [x] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

_No response_

### Describe the bug

If a project only supports snapshots (in this case April Fools snapshots), by default an empty list is shown, which is undesirable.

Image

### Steps to reproduce

1. Go to https://modrinth.com/resourcepack/april-fools-translation
2. Click the "Download" button on the top right
3. Click "Select game version"
4. See empty list

### Expected behavior

The "Show all versions" checkbox should be checked automatically so the list is not empty.

### Additional context

_No response_

### LINKED ISSUE #4226: Loader label on notifications appearing as the same on all lines
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues?q=is%3Aissue) for duplicate problems
- [x] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Chrome (including Arc, Brave, Opera, Vivaldi)

### Describe the bug

When viewing notifications, all the mod loaders seem to show the same, even though they're not matching what was actually posted. Screenshot below:

Image

### Steps to reproduce

1. Go to the notifications dashboard
2. Attempt to view a notification with multiple versions with multiple loaders
3. The loader icon/name does not match the contents of the notification

### Expected behavior

The notification should display the correct loader label. For example, in my screenshot Storage Drawers uploaded 3 different versions, they should be NeoForge, Forge & Fabric, not NeoForge, Neoforge & NeoForge.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by teaSummer**
fix #3821.

fix #4226.

### CODE REVIEW

**Comment by IMB11** [comment]
Fix lint issues by running `pnpm run web:fix" and then LGTM

File: apps/frontend/src/pages/[type]/[id].vue [hunk 1]
```diff
@@ -1664,6 +1664,12 @@ if (!route.name.startsWith('type-id-settings')) {
 const onUserCollectProject = useClientTry(userCollectProject)
 
 const { version, loader } = route.query
+if (
+	project.value.game_versions.length > 0 &&
+	project.value.game_versions.every((v) => v.includes('w') || v.includes('-'))
```
Comment (Prospector) [inline apps/frontend/src/pages/[type]/[id].vue:1669]: this isn't how this should be checked, the release type should be checked in the tags list.

also, it doesn't seem like this hides the check box or anything?

**Review by Prospector — CHANGES_REQUESTED** [review]
