### PR TITLE
Fix inconsistent PAT display order

### LINKED ISSUE #4661: PATs are displayed in random order on the PATs screen
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues?q=is%3Aissue) for duplicate problems
- [x] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Firefox

### Describe the bug

_No response_

### Steps to reproduce

1. Go to Settings > Personal access tokens
2. Make multiple PATs
3. Refresh the page a few times. The ordering changes each time because the API returns them out of order.

### Expected behavior

The PATs are displayed in the same order every time.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by thedarkcolour**
Closes #4661

This fixes the Personal access tokens list under Settings > Personal Access Tokens to display the PATs in order of creation, instead of being in a random order every page load.

### CODE REVIEW

**Comment by Prospector** [comment]
please run pnpm fix:frontend to fix the lint issues

**Comment by Prospector** [comment]
oh actually, this is failing because the computed has a side effect because .sort() mutates the original array

File: apps/frontend/src/pages/settings/pats.vue [hunk 1]
```diff
@@ -332,6 +332,9 @@ const deletePatIndex = ref(null)
 const loading = ref(false)
 
 const { data: pats, refresh } = await useAsyncData('pat', () => useBaseFetch('pat'))
+const displayPats = computed(() => {
+	return pats.value.sort((a, b) => new Date(b.created) - new Date(a.created))
```
Comment (Prospector) [inline apps/frontend/src/pages/settings/pats.vue]: sort mutates pats array, computeds shouldn't have side effects like that

**Review by Prospector — CHANGES_REQUESTED** [review]

File: apps/frontend/src/pages/settings/pats.vue (hunk 1 above)
Comment (thedarkcolour) [reply apps/frontend/src/pages/settings/pats.vue]: Yeah, you're right, I forgot `sort` mutated the array instead of copying it

**Review by Prospector — APPROVED** [review]

**Comment by Prospector** [comment]
_now_ it's lint issues lol. `pnpm fix:frontend`

**Comment by thedarkcolour** [comment]
FYI, I couldn't get that lint fix command to work due to errors with `--filter` in the command (I'm on Windows using pnpm)
I had to change it to this in order to test the linting locally: `"fix:frontend": "turbo run fix --continue --parallel "`

**Comment by Prospector** [comment]
weird, it should work on windows just fine
