### PR TITLE
Fixed a few icons in settings shrinking on mobile

### LINKED ISSUE #2297: Differently sized checkmarks on the mobile website
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Chrome (including Arc, Brave, Opera, Vivaldi)

### Describe the bug

Hi! I hope its okay that I contact you this way. I think I found a bug. It may be intentional but it doesn't really look like it is. On the mobile version of the website, in the billing and subscriptions page if the settings, the checkmarks are differently sized.
I wish you all best wishes and good luck with the future of Modrinth!
Screenshot_20240825-173705_Chrome

### Steps to reproduce

1. Go to setting 
2. Go to billing and subscriptions 

### Expected behavior

I think it would make more sense if they were the same size.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Prospector**
Closes #2297

### CODE REVIEW

File: packages/ui/src/components/settings/ThemeSelector.vue [hunk 1]
```diff
@@ -72,18 +72,18 @@ function asString(theme: T): string {
...
 					v-if="'light' === option"
 					v-tooltip="formatMessage(colorTheme.preferredLight)"
-					class="theme-icon"
+					class="theme-icon shrink-0"
 				/>
 				<MoonIcon
 					v-else-if="'dark' === option"
 					v-tooltip="formatMessage(colorTheme.preferredDark)"
-					class="theme-icon"
+					class="theme-icon shrinkx-0"
```
Comment (vacla) [inline packages/ui/src/components/settings/ThemeSelector.vue]: Shouldn't this be shrink-0?

Comment (Prospector) [reply packages/ui/src/components/settings/ThemeSelector.vue]: yup, thanks

**Review by IMB11 — APPROVED** [review]
