### PR TITLE
Collection descriptions can get out of the collection's box

### LINKED ISSUE #2281: Collection descriptions can get out of the collection's box
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Chrome (including Arc, Brave, Opera, Vivaldi), Microsoft Edge, Firefox

### Describe the bug

Collection descriptions can get out of the collection's box if the description is too long, without any spaces or line breaks

### Steps to reproduce

1. Go to https://modrinth.com/dashboard/collections
2. Click Create Collection
3. Enter anything for the name
4. Fill in a very description, without putting a space, like so:
image

### Expected behavior

The description gets cut off, and get's replaced with `...`

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Pulsar-Programmer**
Fixes #2281

### CODE REVIEW

File: apps/frontend/src/pages/dashboard/collections.vue [hunk 1]
```diff
@@ -202,6 +202,15 @@ const orderedCollections = computed(() => {
...
 				font-size: var(--font-size-sm);
+
+				word-break: break-word;
+				//additional stuff if we specifically want cutoff by elipsis
+				// overflow: hidden;
+				// text-overflow: ellipsis;
+				// line-clamp: 2;
+				// -webkit-line-clamp: 2;
+				// display: -webkit-box;
+				// -webkit-box-orient: vertical;
```
Comment (IMB11) [inline apps/frontend/src/pages/dashboard/collections.vue]:
```suggestion
```
