### PR TITLE
fix(teams): accept username in edit member endpoint

### LINKED ISSUE #2568: PATCH to /team/:id/members/:user fails when used with username rather than ID
### Describe the bug

According to the documentation, the `PATCH team/:id/members/:user` endpoint should accept both the user ID and username for the `:user` pathname parameter [^1]. However, when called with the username, the endpoint will return 401 (Unauthorized) with the error message telling that the current user has no permissions to edit the team, despite being a literal owner of the project.

[^1]: https://docs.modrinth.com/#tag/teams/operation/modifyTeamMember

### Steps to reproduce

1. Send a `PATCH` request to `team/:id/members/:user` with the username as a `:user` pathname parameter.

### Expected behavior

The response succeeds and the member gets changed, just like it does when the user ID used instead.

### Additional context

N/A

### PR DESCRIPTION
**Pull request by Sychic**
Previously, all inputs to the id/username argument were treated as ids regardless of whether they were or not. Now the input is resolved to a user to obtain a user id before proceeding.

Closes #2568

### CODE REVIEW

File: apps/labrinth/src/routes/v3/teams.rs [hunk 1]
```diff
@@ -689,15 +689,23 @@ pub struct EditTeamMember {
...
-    let user_id = ids.1.into();
+
+    let user_id = DBUser::get(&ids.1, &**pool, &redis)
+        .await?
+        .ok_or_else(|| {
+            ApiError::InvalidInput(
+                "The user specified does not exist".to_string(),
+            )
+        })?
+        .id;
```
Comment (aecsocket) [inline apps/labrinth/src/routes/v3/teams.rs]: Should use `.wrap_request_err()` from `crate::util::error::Context`


```suggestion
        .wrap_request_err("specified user does not exist")?
        .id;
```

**Review by aecsocket — CHANGES_REQUESTED** [review]

File: apps/labrinth/src/routes/v3/teams.rs [hunk 2]
```diff
@@ -689,15 +689,19 @@ pub struct EditTeamMember {
...
     edit_member: web::Json<EditTeamMember>,
     redis: web::Data<RedisPool>,
     session_queue: web::Data<AuthQueue>,
 ) -> Result<HttpResponse, ApiError> {
     let ids = info.into_inner();
     let id = ids.0.into();
-    let user_id = ids.1.into();
+
+    let user_id = DBUser::get(&ids.1, &**pool, &redis)
+        .await?
```
Comment (aecsocket) [inline apps/labrinth/src/routes/v3/teams.rs]: nit: database ops should have a `.wrap_internal_err("failed to fetch ...")`

File: apps/labrinth/src/routes/v3/teams.rs [hunk 3]
```diff
@@ -709,24 +713,19 @@ pub async fn edit_team_member(
...
     .1;
 
-    let team_association =
-        DBTeam::get_association(id, &**pool).await?.ok_or_else(|| {
-            ApiError::InvalidInput(
-                "The team specified does not exist".to_string(),
-            )
-        })?;
+    let team_association = DBTeam::get_association(id, &**pool)
+        .await?
```
Comment (aecsocket) [inline apps/labrinth/src/routes/v3/teams.rs]: nit: database ops should have a `.wrap_internal_err("failed to fetch ...")`

File: apps/labrinth/src/routes/v3/teams.rs [hunk 4]
```diff
@@ -709,24 +713,19 @@ pub async fn edit_team_member(
...
+        .wrap_request_err("The team specified does not exist")?;
     let member =
         DBTeamMember::get_from_user_id(id, current_user.id.into(), &**pool)
             .await?;
     let edit_member_db =
         DBTeamMember::get_from_user_id_pending(id, user_id, &**pool)
             .await?
```
Comment (aecsocket) [inline apps/labrinth/src/routes/v3/teams.rs]: nit: database ops should have a `.wrap_internal_err("failed to fetch ...")`

**Review by aecsocket — APPROVED** [review]
